### ISSUE TITLE
Problem showing smiley popup inside own div

### ISSUE THREAD

**Issue by danman1234** [mervick/emojionearea#130]
```
<div class="textarea" data-placeholder="Add a comment about your experience" contenteditable="true" style="height: 3.65em;"></div>
```

I have my own layout with textarea as class

now whn i do:

```
$(".textarea").emojioneArea({
    hideSource      : true,
    autoHideFilters : true,
    useSprite       : true
}); 
```
Well i see the smiley icon at the right side, but when i click on it nothing is shown. If i examine the console, then i see the code is there, but it conflicts. I dont want the smiley to popup inside this element, but it should be outside. If i use standalone, then it is shown, but i cant set a target after i click a smiley it should go in the .textarea element. Also i have many .textarea classes, how to set an event handler to show the smiley icon after the class has been clicked?

**TODO**
* [x] Add option for removing search bar
* [x] Fix saveEmojisAs option

**Comment by mervick** [comment]
Please put your code in jsfiddle https://jsfiddle.net/1v03Lqnu/12/, and share result

**Comment by danman1234** [comment]
i have solved it, because it coflicted with another .textarea class that i was using.
I am using http://viima.github.io/jquery-comments/ and when i use this:

`			var el = $('#'+disid).emojioneArea({
					pickerPosition: "bottom",
					useSprite         : true,    
				});	 `

check this elelement how i use it:

`
<div class="textarea-wrapper" style="width: 1192px;"><span class="close" style="display: block;"><span class="left"></span><span class="right"></span></span>
<div class="textarea" id="zwq29" data-placeholder="Add a comment about your experience" contenteditable="true" style="height: 3.65em; display: none;">ssdddfggg</div>

<div class=emojionearea textarea>...... </div>
</div>

`
on click, then in the source div (.textarea with the id tag), when i show it,  i can type fast. but when i use the  emojionearea div, then typing text goes soooooooooo slowwwwww, what is up with that??

**Comment by danman1234** [comment]
Here i got an update:

I know why it became so slow when typing. This has to do with the overload of images.
- I deleted in enojionearea.js 70% of alle the smilies. Then it was fast as a train. Otherwise it would be very slow.
- I see that everything is in unicode, even if i set the option to image:
  saveEmojisAs      : "unicode", // unicode | shortname | image

- it still uses unicode. Is there a way to reverse the unicode back to the coloured image? I save it in mysql and how to show images when i retrieve it?

- Why there is no option to remove the search bar?

**Comment by mervick** [comment]
* [ ] Add option for removing search bar

**Comment by mervick** [comment]
> it still uses unicode. Is there a way to reverse the unicode back to the coloured image? I save it in mysql and how to show images when i retrieve it?

Please use search across [issues](https://github.com/mervick/emojionearea/issues), there are a lot of duplicated questions

**Comment by mervick** [comment]
> I see that everything is in unicode, even if i set the option to image:
saveEmojisAs : "unicode", // unicode | shortname | image

Seems like it broken in last release, try to use [v3.1.6](https://github.com/mervick/emojionearea/releases/tag/v3.1.6)
